# Generated by Django 2.1.7 on 2019-02-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
